#! /usr/local/bin/bash

# Recreate the requirement_blocks table, using the latest available csv file from OIRA.
(
  # Command line option to skip download step
  if [[ $# -gt 0 &&  ( "$1" == "--skip-download") || ( "$1" == "-sd" ) ]]
  then echo 'Skip download step'
  else
    echo -n 'Get latest dap_req_block ...'
    # Download new dgw_dap_req_block.csv if there is one from OIRA
    if [[ `hostname` != 'cvlaptop.local' && `hostname` != 'cvhome.local' ]]
    then
          export LFTP_PASSWORD=`cat /Users/vickery/.lftpwd`
          /usr/local/bin/lftp -f ./getcunyrc
          if [[ $? != 0 ]]
          then echo Download failed
               exit
          fi
          # Check file is "big enough" and delete it if not

    fi
    echo done
  fi

  cd /Users/vickery/CUNY_Programs/dgw_info
  export latest='./downloads/dap_req_block.csv'
  if [[ ! -e downloads/dgw_dap_req_block.csv ]]
  then  # Find the latest file in the archives folder
    shopt -s nullglob
    all=(./archives/dgw_dap*)
    n=$(( ${#all[@]} - 1 ))
    if (( $n < 0 ))
    then
      latest=''
      echo "ERROR: no dgw_dap_req_block.csv files found"
      exit 1
    else
      latest=${all[$n]}
      cp $latest ./downloads/dgw_dap_req_block.csv
      echo "No new dap_req_block.csv in downloads. Using $latest."
    fi
  fi
  SECONDS=0
  echo "Start cuny_requirement_blocks.py"
  ./cuny_requirement_blocks.py
  SECONDS=0
  echo "End cuny_requirement_blocks.py after $SECONDS seconds"

  echo "Start dgw_driver"
  export PYTHONPATH=/Users/vickery/dgw_processor:/Users/vickery/Transfer_App
  python3 -m dgw_driver -i all -t all -v all
  echo "End dgw_driver after $SECONDS seconds"
)
